apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: salesappAsiaKubeDev-rg
  name: identityserver-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  loadBalancerIP: 20.166.66.243
  type: LoadBalancer
  selector:
    app: IdentityServer